export interface Award {
  awardid: number;
  worldid: number;
  assetglburl: string;
  assetusdzurl: string;
  googledrive: string | null;
  assettemplate: string;
  geolocation: string | null;
  awardimg: string;
  description: string;
  videolocation: string;
  userid: string;
  assetname: string;
  type: string;
  name: string;
  price?: string | null;
  currency?: string | null;
  certifyingbody: string;
  address: string;
  latitude: string;
  longitude: string;
  allowed_radius: string;
  tokenuri: string | null;
  tokenurl: string | null;
  locationname: string;
  locationtype: string;
  dropname: string;
  vertical: string;
  textbook: string;
  challenge: string;
  redeemed: number;
  htmltext: string;
  public: string;
  created_at: string;
  updated_at: string;
  publicurl?: string;
  privateurl?: string;
  worldname?: string;
  worldimg?: string;
}
