import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from '../contexts/AuthContext';
import Script from 'next/script'

const baseFont = localFont({
  src: [
    {
      path: "../../public/fonts/GeneralSans-Extralight.otf",
      weight: "200",
    },
    {
      path: "../../public/fonts/GeneralSans-Light.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/GeneralSans-Regular.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/GeneralSans-Medium.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/GeneralSans-Semibold.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/GeneralSans-Bold.otf",
      weight: "700",
    },
  ],
  fallback: ["Helvetica", "ui-sans-serif"],
  variable: "--font-base",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Geo-Drops",
  description: "Generated by Geo-Drops",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* In your app/layout.tsx or page head */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <Script 
          src="https://cdn.jsdelivr.net/npm/exif-js" 
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${baseFont.variable}  bg-[#EEEFF3] dark:bg-[#1C2541] dark:text-white font-sans tracking-tight text-primary`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
